### ISSUE TITLE
ImportError: cannot import name 'NDArray' from 'numpy.typing'

### ISSUE THREAD

**Issue by AlexWindels** [JR-1991/sdrdm-template#3]
I am experimenting with this software and copied the first lines from following notebook: https://github.com/PyEED/PyEED-jupyternotebook/blob/936e7bb1d5e83df1dd10dbd64459433b4d77e5d2/DatamodelExample0_3.ipynb. I however get following error: ImportError: cannot import name 'NDArray' from 'numpy.typing' (/Users/winde/opt/anaconda3/lib/python3.9/site-packages/numpy/typing/__init__.py)

I have verified that NumPy is installed (version 1.24.2) and I am running on Python 3.9.7. Attached you can find the Notebook I tried it in. Any suggestions on how I can resolve the issue?

<img width="1097" alt="image" src="https://user-images.githubusercontent.com/72694200/218787772-ce6c36a9-c49a-4105-9d57-ed11b6a31c28.png">
<img width="1021" alt="image" src="https://user-images.githubusercontent.com/72694200/218787917-53baa1c0-16d8-4cfa-9d5b-ee64e08bb339.png">
<img width="1111" alt="image" src="https://user-images.githubusercontent.com/72694200/218788016-8e6c7961-f1eb-4411-bda0-6ea9baecbff3.png">

**Comment by JR-1991** [comment]
Thank you for submitting your issue, Alex!

After testing with Numpy version `1.24.2` and looking at your log, it seems that your current Numpy version is `1.20.3` and the `NDArray` is not part of the typing module for this version. It is possible that the kernel used in your notebook is different from your terminal, causing the discrepancy. 

To update your kernel's Numpy version, try running the following code in your notebook: 

```python
import sys 
!{sys.executable} -m pip install --upgrade numpy
```

This should resolve the issue. Please let me know if it worked. I have also opened an issue at sdRDM to specify versions in the setup to prevent incompatibilities.

**Comment by AlexWindels** [comment]
Hi Jan, thank you so much for your reply! I tried what you proposed (as seen in the image below), yet that unfortunately didn't resolve the issue. Any more ideas? :)
<img width="1014" alt="image" src="https://user-images.githubusercontent.com/72694200/219043473-037f0e32-2c70-4647-b1ba-8ef62db3e4b4.png">
<img width="1018" alt="image" src="https://user-images.githubusercontent.com/72694200/219043645-a85196b9-4a65-44a1-b7cc-f919043bef29.png">

**Comment by JR-1991** [comment]
Alright, it seems like there are dependency issues caused by your SciPy and Numba versions. You can use `conda` or `venv` to set up a local environment to prevent such dependency problems. I just changed the typing from `NDArray` to `ArrayLike` which is supported by older versions. Can you try to re-install it?

**Comment by AlexWindels** [comment]
Hi Jan, creating a virtual environment solved the issue! Thank you for your help!
